### ISSUE TITLE
[Helm Chart] plugin/loop: no next plugin found

### ISSUE THREAD

**Issue by Diaoul** [ori-edge/k8s_gateway#136]
Running the helm chart with most values default, here is what the log is on startup.

```
[INFO] 127.0.0.1:33633 - 41080 "HINFO IN 8237687624183295910.7537598229432224564. udp 57 false 512" - - 0 0.00005595s
[ERROR] plugin/errors: 2 8237687624183295910.7537598229432224564. HINFO: plugin/loop: no next plugin found
```

It seems there is an issue with the loop plugin configuration when no forwarder is set?

**Comment by networkop** [comment]
Hi @Diaoul , can you include your helm chart values you used and the command to install it?

**Comment by Diaoul** [comment]
Installed using fluxcd: https://github.com/Diaoul/home-ops/commit/28fa1ee2b90236c7dc8a4d01f62d822a324bdadc#diff-a86e1e8b391bf413635e508861f9f23770e923047852350990e882acf9aaea85R18
```yaml
    image:
      repository: oriedge/k8s_gateway
      tag: v0.3.1
    domain: ${DOMAIN}
    service:
      type: LoadBalancer
      externalIPs:
        - ${K8S_GATEWAY_IP}
      externalTrafficPolicy: Local
```
