### ISSUE TITLE
Traefik IngressRoute Support?

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [ori-edge/k8s_gateway#162]
https://doc.traefik.io/traefik/providers/kubernetes-crd/

Would it be feasible to request support for Traefik's IngressRoute kind?

**Comment by XtremeOwnageDotCom** [comment]
Apparently, its extremely easy to do. Just setup a dummy Ingress.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: homeassistant
  annotations:
    coredns.io/hostname: "hass.kube.mydomain.com"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`hass.kube.mydomain.com`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homeassistant-external-dns
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: hass.kube.mydomain.com
   
```
