### ISSUE TITLE
Support services with ExternalIPs using `coredns.io/hostname`

### ISSUE THREAD

**Issue by onedr0p** [ori-edge/k8s_gateway#185]
Hi 👋🏼  I have a loadbalancer service with using external IPs instead of a load balancer IP. It would be great if I could use the `coredns.io/hostname` annotation on this service.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    coredns.io/hostname: postgres.domain.tld
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
  name: postgres
  namespace: default
spec:
  externalIPs:
  - 192.168.69.113
  externalTrafficPolicy: Local
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresql: postgres
    role: primary
  type: LoadBalancer
# Status is not being populated on viewing the status of this service
# status:
#   loadBalancer: {}
```
