### ISSUE TITLE
Pod doesn't start when forward plugin is configured

### ISSUE THREAD

**Issue by sfenzke** [ori-edge/k8s_gateway#198]
I had the forward plugin configured like thist:
```
extraZonePlugins:
  - name: forward
    parameters: . 192 168 178.2
```
This lead to the pod not starting anymore. The issue seems to be existing since Chart version 2.0.0. 
Am I doing something wrong or is there an issue wit the service?

**Comment by networkop** [comment]
what is the error you're seeing? I can see you've misspelled the IP "192.168.178.2", could this be the issue?

**Comment by sfenzke** [comment]
Hello I just confirmed the missplelled IP is not in my configuration. The error I am seeing is that the pod never reaches the ready state and starts to ansewer to DNS Requests. Unfortunatley there is no error message. The log outout of the pod is like this:
`[INFO] plugin/k8s_gateway: Building k8s_gateway controller
[INFO] plugin/k8s_gateway: GatewayAPI CRDs are not found. Not syncing GatewayAPI resources.
[INFO] plugin/k8s_gateway: VirtualServer CRDs are not found. Not syncing VirtualServer resources.
[INFO] plugin/k8s_gateway: Starting k8s_gateway controller
[INFO] plugin/k8s_gateway: Waiting for controllers to sync
.:1053
CoreDNS-1.10.0+k8s_gateway-0.3.3
linux/arm64, go1.19.5, bce972a
[INFO] plugin/k8s_gateway: Synced all required resources`

**Comment by networkop** [comment]
ok, got it. can you please include your values file? I'll test it today/tomorrow

**Comment by sfenzke** [comment]
Hi sorry for the late reply. Here is the content of my values file:

<pre>
domain: "sfenzke-home.de"

extraZonePlugins:
  - name: forward
    parameters: . 192.168.178.2

service:
  type: LoadBalancer
  port: 53
  annotations: {metallb.universe.tf/address-pool: dns-pool}
  externalIPs:
    - 192.168.6.2
</pre>

**Comment by networkop** [comment]
cool, will test in a couple of days and push the fix

**Comment by networkop** [comment]
I think i've found the issue. Can you retest with the following values file:
```
domain: "sfenzke-home.de"

extraZonePlugins:
  - name: forward
    parameters: . 192.168.178.2
  - name: ready

service:
  type: LoadBalancer
  port: 53
  annotations: {metallb.universe.tf/address-pool: dns-pool}
  externalIPs:
    - 192.168.6.2
 ```
