### ISSUE TITLE
Support other Gateway API route types

### ISSUE THREAD

**Issue by larivierec** [ori-edge/k8s_gateway#237]
Currently k8s_gateway plugin only supports HTTPRoute.

It will most probably be beneficial to others to also support:

- TLSRoute
- GRPCRoute

Ref spec: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: example
  namespace: default
spec:
  parentRefs:
    - name: cilium-internal
      namespace: infrastructure
  hostnames:
    - "example.test.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: example
        port: 8080
```
