### ISSUE TITLE
DNS cannot be resolved for HTTPRoute

### ISSUE THREAD

**Issue by StoveCode** [ori-edge/k8s_gateway#242]
First of all, this is a great tool :) *thank you*

I currently have a problem with the "Kubernetes Gateway API"
DNS requests are not resolved.
installed with Helm -> latest release

Logs
```
[INFO] 172.16.210.192:30184 - 6257 "A IN httpbin1.test.de udp 66 true 4000" NOERROR qr,aa,ra 180 0.000317369s
[DEBUG] plugin/k8s_gateway: Computed Index Keys [httpbin1.test.de httpbin1]
[DEBUG] plugin/k8s_gateway: Found 0 matching VirtualServer objects
[DEBUG] plugin/k8s_gateway: Found 0 matching Ingress objects
[DEBUG] plugin/k8s_gateway: Found 0 matching Service objects
[DEBUG] plugin/k8s_gateway: Computed response addresses []
```

*As you can see here, the recource httproute is not looked at, so nothing can be resolved*

Is this problem expected to be fixed?

**Comment by networkop** [comment]
This is most likely due to gateway not having an IP assigned which could be either metalLB (or whatever LB provider) not assigning an IP. Or it could be due to Istio not doing its work, e.g. latest releases of Istio stopped supporting old GwAPI CRDs. There are a couple of open PRs update the supported version of CRDs to 1.0

**Comment by StoveCode** [comment]
Thank you for your explanation I think this is more due to the istio problem
I have recently updated to 1.20

**Comment by larivierec** [comment]
Istio would have to support gateway apis 1.0+.
If this is the case, it should work defacto

**Comment by larivierec** [comment]
Have you tried the latest istio gw? 

https://tetrate.io/blog/whats-new-in-istio-120-gateway-api-external-endpoint-enhancements-wasm-updates-and-more/#

V1.20

**Comment by Apocrathia** [comment]
Same thing using the Cilium backend for the gateway API. It's possibly an issue with Cilium not returning the address, but it definitely has one. 

```
[DEBUG] plugin/k8s_gateway: Computed Index Keys [longhorn-ui.k8s.apocrathia.com longhorn-ui]
[DEBUG] plugin/k8s_gateway: Found 1 matching httpRoute objects
[DEBUG] plugin/k8s_gateway: Found 0 matching gateway objects
[DEBUG] plugin/k8s_gateway: Found 0 matching tlsRoute objects
[DEBUG] plugin/k8s_gateway: Found 0 matching grpcRoute objects
[DEBUG] plugin/k8s_gateway: Found 0 matching Ingress objects
[DEBUG] plugin/k8s_gateway: Found 0 matching Service objects
[DEBUG] plugin/k8s_gateway: Computed response addresses []
[INFO] 10.100.0.179:49772 - 39844 "A IN longhorn-ui.k8s.apocrathia.com. udp 48 false 512" NXDOMAIN qr,aa,rd 197 0.000221408s
```

**Comment by larivierec** [comment]
Is your manifest public? Can you link it, I'm curious?

**Comment by Apocrathia** [comment]
@larivierec It's not, but I'm just installing via the helm chart via flux. Here's what I've got:

```yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: datasource=helm registryUrl=https://ori-edge.github.io/k8s_gateway/
      chart: k8s-gateway
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Delegated domain
    domain: "k8s.apocrathia.com"

    # TTL for non-apex responses (in seconds)
    ttl: 300

    # Resources (CPU, memory etc)
    resources: {}

    # Limit what kind of resources to watch, e.g. watchedResources: ["Ingress"]
    watchedResources: []

    # Service name of a secondary DNS server (should be `serviceName.namespace`)
    secondary: ""

    # Enabled fallthrough for k8s_gateway
    fallthrough:
      enabled: false
      zones: []

    # Override the default `serviceName.namespace` domain apex
    apex: "k8s.apocrathia.com"

    # Optional configuration option for DNS01 challenge that will redirect all acme
    # challenge requests to external cloud domain (e.g. managed by cert-manager)
    # See: https://cert-manager.io/docs/configuration/acme/dns01/
    dnsChallenge:
      enabled: false
      domain: dns01.clouddns.com

    # Optional plugins that will be enabled in the zone, e.g. "forward . /etc/resolve.conf"
    extraZonePlugins:
      - name: log
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: loop
      - name: reload
      - name: loadbalance

    serviceAccount:
      create: true
      name: "k8s-gateway"
      annotations: {}

    service:
      type: LoadBalancer
      port: 53
      annotations: {}
      # nodePort: 30053
      loadBalancerIP: 10.50.8.53 # ARP
      # clusterIP: 10.43.0.53
      # externalTrafficPolicy: Local
      # externalIPs:
      #   - 10.0.8.53 # BGP
      #   - 10.50.8.53 # ARP
      # One of SingleStack, PreferDualStack, or RequireDualStack.
      # ipFamilyPolicy: SingleStack
      # List of IP families (e.g. IPv4 and/or IPv6).
      # ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
      # ipFamilies:
      #   - IPv4
      #   - IPv6

    nodeSelector: {}

    affinity: {}

    replicaCount: 1

    # Optional PriorityClass that will be used in the Deployment, e.g. priorityClassName: "system-cluster-critical"
    priorityClassName: ""

    debug:
      enabled: true

    secure: true

    zoneFiles: []
    #    - filename: example.db
    #      # Optional
    #      domains: example.com
    #      contents: |
    #        example.com.   IN SOA sns.dns.icann.com. noc.dns.icann.com. 2015082541 7200 3600 1209600 3600
    #        example.com.   IN NS  b.iana-servers.net.
    #        example.com.   IN NS  a.iana-servers.net.
    #        example.com.   IN A   192.168.99.102
    #        *.example.com. IN A   192.168.99.102
```
It's a pretty basic deployment. ¯\_(ツ)_/¯
