### ISSUE TITLE
Question : Can it be used for cicd ?

### ISSUE THREAD

**Issue by survivant** [ori-edge/k8s_gateway#31]
here my usecase.  I want to deploy my applications on multiple namespaces

- dev
- qa
- PR-111  (for Pull request)

my services could look like that

chuck-service:8080
quote-service:8080

I'm on premise with nginx-ingress and with metallb as loadbalancer

I'll expose nginx-controler as daemonset with a external IP : 10.1.10.123

for ingress

/chuck  -> chuck-service:8080
/quote -> quote-service:8080

I want to have those applications to be accessible for from outside on 10.1.10.123 (I can't expose new IP)

the domain (inside-my-company.com) name it not register in external DNS

ex : 
dev.inside-my-company.com/chuck 
dev.inside-my-company.com/quote

qa.inside-my-company.com/chuck 
qa.inside-my-company.com/quote

....

**Comment by networkop** [comment]
yeah, that should work out of the box. As soon as you define an Ingress, this plugin will return the IP of your ingress controller for every unique hostname of your Ingresses.

**Comment by survivant** [comment]
How can I do that ? For now I only have one version and it’s in the default namespace. like
````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chuck
  annotations:
    # this important https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/references/annotations/#konghqcomstrip-path
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /quote
            pathType: Prefix
            backend:
              service:
                name: reactive-quote-service
                port:
                  number: 8080
          - path: /chuck
            pathType: Prefix
            backend:
              service:
                name: chuck-quote-service
                port:
                  number: 8080
````
Here the list of my services. Kong is my ingress controller
````
vagrant@enroute-master:~$ kubectl get svc --all-namespaces
NAMESPACE     NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
default       chuck-quote-service       ClusterIP      10.110.149.200   <none>           8080/TCP                     12h
default       exdns-k8s-gateway         LoadBalancer   10.109.67.179    192.168.50.202   53:30186/UDP                 11h
default       kubernetes                ClusterIP      10.96.0.1        <none>           443/TCP                      13h
default       reactive-quote-service    ClusterIP      10.108.148.54    <none>           80/TCP                       12h
kong          kong-proxy                LoadBalancer   10.103.175.232   192.168.50.200   80:30092/TCP,443:31098/TCP   12h
kong          kong-validation-webhook   ClusterIP      10.110.25.248    <none>           443/TCP                      12h
kube-system   exdns-2-k8s-gateway       LoadBalancer   10.105.96.51     192.168.50.203   53:30389/UDP                 11h
kube-system   ext-dns-tcp               LoadBalancer   10.111.101.102   192.168.50.201   53:32759/TCP                 11h
kube-system   ext-dns-udp               LoadBalancer   10.110.14.237    192.168.50.201   53:31119/UDP                 11h
kube-system   kube-dns                  ClusterIP      10.96.0.10       <none>           53/UDP,53/TCP,9153/TCP       13h
test          chuck-quote-service       ClusterIP      10.109.213.53    <none>           8080/TCP                     12h
test          reactive-quote-service    ClusterIP      10.106.129.43    <none>           80/TCP                       12h
vagrant@enroute-master:~$
````
I have 2 applications
````
    chuck-quote-service
    reactive-quote-service
````
For those 2 applications, I want to deploy them in dev, qa… namespaces and modify the ingress rules for that.and I need to access those applications from outside my cluster, like
````
http://dev.example.org/chuck
http://qa.example.org/chuck
````
I’m looking to reproduce that setup on bare-metal with kubernetes 1.20 configured with kubeadm.
